### ISSUE TITLE
Create main_data_processor

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dane-whisper-asr-worker#1]
A module that can be called from the worker.py to do the actual processing

**Comment by greenw0lf** [comment]
Video I used for testing: https://www.openbeelden.nl/media/628918/G%C3%BClers_Travels_4

It can be downloaded, run through [dane-audio-extraction-worker](https://github.com/beeldengeluid/dane-audio-extraction-worker/), then the resulting audio can be used for testing
