### ISSUE TITLE
Try out Whisper-X

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dane-whisper-asr-worker#36]
Deploy and run WhisperX

**Comment by greenw0lf** [comment]
UPDATE: 
- `batch_size = 24` works the best (91% GPU memory usage, fastest overall)
- `batch_size = 26` was <1s faster for 1 hr audio file and consumed around 97% GPU memory. Overall it was still slower by <1s than size 24. Very close to running OOM => NOT SUITABLE

Next step: Run WhisperX evaluation using `batch_size = 24`
