### ISSUE TITLE
Report processing times in provenance in ms instead of s (where needed)

### ISSUE THREAD

**Issue by greenw0lf** [beeldengeluid/dane-whisper-asr-worker#45]

**Comment by Veldhoen** [comment]
I think actually the other way around; we should report everything in ms (at least, that's the standard we set in https://github.com/CLARIAH/DANE/blob/main/dane/provenance.py)

**Comment by greenw0lf** [comment]
Ok, changing the title then

**Comment by greenw0lf** [comment]
Nevermind, found the issues!

1. In `io_util.py`, for `obtain_input_file()`, the processing time was not multiplied by 1000 to report in ms instead of s.
2. Time in the Whisper ASR provenance bit was also a bit wrong: ms for `start_time_unix` instead of s
3. the `DANE` Python package hasn't been updated to the latest version, which fixes this processing time issue of reporting it in s instead of ms as expected.
